# Generated by Django 2.0.6 on 2018-06-09 23:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='2018-06-10 01:37:23.370672', max_length=40)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la imagen')),
                ('thumbnail', models.ImageField(height_field=500, upload_to='thumbs', width_field=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última edición')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('ubicacion', models.CharField(max_length=80)),
                ('fecha_evento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id_multimedia', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='image2018-06-10 01:37:23.371574', max_length=80)),
                ('descripción', models.TextField(blank=True, help_text='Descríbeme...')),
                ('path', models.FilePathField(allow_folders=True, path='media')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('Galeria.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('multimedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Galeria.Multimedia')),
                ('image_width', models.PositiveSmallIntegerField(default=640)),
                ('image_height', models.PositiveSmallIntegerField(default=480)),
                ('imagen', models.ImageField(height_field=models.PositiveSmallIntegerField(default=480), upload_to='files/img', verbose_name='Archivo de imagen', width_field=models.PositiveSmallIntegerField(default=640))),
            ],
            bases=('Galeria.multimedia',),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Galeria.Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Galeria.Evento'),
        ),
        migrations.AddField(
            model_name='album',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='familiar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Administrador', to='Galeria.Familiar'),
        ),
    ]
