# Generated by Django 2.0.6 on 2018-06-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-10 01:58:30.589312', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-10 01:58:30.590195', max_length=80),
        ),
    ]
