# Generated by Django 2.0.6 on 2018-06-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0003_auto_20180610_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-10 02:13:16.219044', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-10 02:13:16.219944', max_length=80),
        ),
    ]
