# Generated by Django 2.0.6 on 2018-06-11 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0004_auto_20180610_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('multimedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Galeria.Multimedia')),
                ('image_width', models.PositiveSmallIntegerField(default=640)),
                ('image_height', models.PositiveSmallIntegerField(default=480)),
                ('fichero_imagen', models.ImageField(height_field=models.PositiveSmallIntegerField(default=480), upload_to='files/img', verbose_name='Archivo de imagen', width_field=models.PositiveSmallIntegerField(default=640))),
            ],
            bases=('Galeria.multimedia',),
        ),
        migrations.RemoveField(
            model_name='image',
            name='multimedia_ptr',
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 15:46:06.789452', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 15:46:06.790491', max_length=80),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
