# Generated by Django 2.0.6 on 2018-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0005_auto_20180611_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='familiar',
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 15:49:23.277752', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 15:49:23.278562', max_length=80),
        ),
    ]
