# Generated by Django 2.0.6 on 2018-06-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0007_auto_20180611_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 18:27:43.339408', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 18:27:43.340215', max_length=80),
        ),
    ]
