# Generated by Django 2.0.6 on 2018-06-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0010_auto_20180611_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='album',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbs'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 18:56:03.581970', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 18:56:03.582790', max_length=80),
        ),
    ]
