# Generated by Django 2.0.6 on 2018-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0011_auto_20180611_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image_height',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='album',
            name='image_width',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='album',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del Álbum'),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(height_field=models.IntegerField(default=400), upload_to='thumbs', width_field=models.IntegerField(default=400)),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 19:16:24.389883', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 19:16:24.390751', max_length=80),
        ),
    ]
