# Generated by Django 2.0.6 on 2018-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0012_auto_20180611_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_width',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(height_field=models.CharField(max_length=10), upload_to='thumbs', width_field=models.CharField(max_length=10)),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 19:21:12.707580', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 19:21:12.708390', max_length=80),
        ),
    ]
