# Generated by Django 2.0.6 on 2018-06-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0013_auto_20180611_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_height',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='album',
            name='image_width',
            field=models.PositiveSmallIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(height_field='image_height', upload_to='thumbs', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 19:36:58.586216', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 19:36:58.587034', max_length=80),
        ),
    ]
