# Generated by Django 2.0.6 on 2018-06-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0014_auto_20180611_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 20:37:05.322677', max_length=40),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='fichero_imagen',
            field=models.ImageField(height_field='image_height', upload_to='files/img', verbose_name='Archivo de imagen', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 20:37:05.323493', max_length=80),
        ),
    ]
