# Generated by Django 2.0.6 on 2018-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0016_auto_20180611_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-11 21:04:59.625374', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-11 21:04:59.626204', max_length=80),
        ),
    ]
