# Generated by Django 2.0.6 on 2018-06-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0017_auto_20180611_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id_keyword', models.AutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-12 21:50:17.371041', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-12 21:50:17.371851', max_length=80),
        ),
        migrations.AddField(
            model_name='multimedia',
            name='keyword',
            field=models.ManyToManyField(to='Galeria.Keyword'),
        ),
    ]
