# Generated by Django 2.0.6 on 2018-06-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0018_auto_20180612_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-12 21:52:27.106191', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-12 21:52:27.107006', max_length=80),
        ),
    ]
