# Generated by Django 2.0.6 on 2018-06-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0021_auto_20180612_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Álbunes'},
        ),
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-12 22:04:07.990837', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-12 22:04:07.991716', max_length=80),
        ),
    ]
