# Generated by Django 2.0.6 on 2018-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0023_auto_20180612_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='descripción',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descríbeme...'),
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-12 22:14:33.645151', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='keyword',
            field=models.ManyToManyField(help_text='Selecciona las Personas que aparezcan en la foto.', to='Galeria.Keyword'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-12 22:14:33.646199', max_length=80),
        ),
    ]
