# Generated by Django 2.0.6 on 2018-06-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galeria', '0024_auto_20180612_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimedia',
            old_name='descripcion',
            new_name='descripción',
        ),
        migrations.AlterField(
            model_name='album',
            name='titulo',
            field=models.CharField(default='2018-06-12 22:14:48.968187', max_length=40),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='titulo',
            field=models.CharField(default='image2018-06-12 22:14:48.969035', max_length=80),
        ),
    ]
